[project]
name = "npc"
version = "0.4.2a0"
description = "A powerful core for building feature-rich Nicotine+ plugins with ease."
authors = [{ name = "Nachtalb", email = "na@nachtalb.io" }]
license = "LGPL-3.0-only"
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = []

[dependency-groups]
dev = [
  { include-group = "docs" },
  "ruff-lsp",
  "black",
  "isort",
  "mypy",
  "ipdb",
  "pre-commit",
]
docs = [
  "sphinx",
  "furo",
  "sphinx-paramlinks",
  "sphinx-copybutton",
  "sphinx-inline-tabs",
  "sphinxcontrib-mermaid",
  "enum-tools[sphinx]",
]

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
preview = true
target-version = ["py39"]

[tool.ruff]
line-length = 120
target-version = "py39"

[tool.mypy]
python_version = "3.9"
show_error_codes = true
pretty = true
strict = true

[[tool.mypy.overrides]]
module = ["pynicotine.*", "sphinx.*"]
ignore_missing_imports = true

[project.scripts]
build-docs = "scripts:build_docs"
open-docs = "scripts:open_docs"
check = "scripts:check"
build-changelog = "scripts:build_changelog"
release = "scripts:release"
change-version = "scripts:change_version"

[tool.uv]
package = true

[tool.uv.build-backend]
namespace = true
module-name = "npc"
module-root = ""

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"
